declare module "lodash" {
  function head<T>(array: T[]): T | undefined;
}
//function hasIn(...): ...
//function isBoolean(...): ...
//function toString(...): ...
//function split(...): ...
//function hasPath(...): ...
//function filter(...): ...
//function every(...): ...
//function map(...): ...
